---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
   - name: Checking to see if system is already joined to AD
     command: /bin/bash -c "net ads info | grep gemini"
     register: adJoin_results
     tags: ad

   - name: Debug realm_list_results
     debug:
     msg: "{{ adJoin_results.stdout }}"
