---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
   - name: Check if machine is bound
     shell: /bin/bash -c "net ads info | grep gemini"
     register: ad_join
     changed_when: false
     ignore_errors: true
     
   - name: Echo active directory
     command: echo "active directory not joined"
     when: ad_join is failed
