---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
   - name: Check if machine is bound
      command: "realm list | grep gemini"
      register: realmd_bound
      changed_when: false
      ignore_errors: true
