---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
   - name: install realmd
     yum:
       name: realmd
       state: present
       
   - name: Check if machine is bound
     command: /bin/adcheck.sh
     register: realmd_bound
     changed_when: false
     ignore_errors: true
     
   - name: Echo active directory
     command: echo "active directory not joined"
     when: realmd_bound is failed
