---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
   - name: Check if machine is bound
      cmd: /usr/bin/adcheck.sh
      register: realmd_bound
      changed_when: false
      ignore_errors: true
