---
- name: browserupdate
  hosts: host1
  
  tasks:
    - name: Chrome update
      yum: name=google-chrome-stable state=latest
    
    - name: Firefox update
      yum: name=firefox.x86_64 state=latest
