---
- hosts: all
  become: true
  become_method: sudo
  
  
  tasks:
    - name: Chrome update
      yum: name=google-chrome-stable state=installed
     
    
    - name: Firefox update
      yum: name=firefox.x86_64 state=latest
