---
- name: browserupdate
  hosts: all
  become: yes
  become_method: sudo
  
  
  tasks:
    - name: Chrome update
      yum: name=google-chrome-stable state=latest
    
    - name: Firefox update
      yum: name=firefox.x86_64 state=latest
