---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
    - name: Ensure that Chrome is updated
      yum: name=google-chrome-stable state=latest
     
    
    - name: Firefox update
      yum: name=firefox state=latest
