---
- hosts: all
  
  
  
  tasks:
    - name: Chrome update
      yum: name=google-chrome-stable state=installed
      become: yes
      become_method: sudo
    
    - name: Firefox update
      yum: name=firefox.x86_64 state=latest
