---
- hosts: all
  sudo: yes
  
  
  tasks:
    - name: Ensure that Chrome is updated
      yum: name=google-chrome-stable state=latest
     
    
    - name: Firefox update
      yum: name=firefox state=latest
