---
- hosts: all
  become: yes
  become_method: sudo
  
  tasks:
    - name: Update Cache
      yum: update_cache=yes
      when: ansible_os_family == "RedHat"
      
    - name: Install Updates
      yum: name= * state=latest
      when: ansible_os_family == "RedHat"
  
